server:
  port: 9030
eureka:
  client:
    service-url:
      defaultZone: http://server2:8082/eureka/
  instance:
    prefer-ip-address: true
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
user:
  config:
    id: 99999
    user-name: 李四
    birthday: '2021-06-25 11:37:37'